version: '2'

services:
  blog:
    image: ghost:1.24.5-alpine
    ports:
      - 2368:2368
    volumes:
      - ./data:/var/lib/ghost/content
    environment:
      - VIRTUAL_PORT=2368
      - VIRTUAL_HOST=blog.lb.jorgeadolfo.com
      - LETSENCRYPT_HOST=blog.lb.jorgeadolfo.com
      - LETSENCRYPT_EMAIL=7jagjag@gmail.com
